spring.application.name=Employee Performance Monitoring
spring.data.mongodb.uri=${MONGO_URI:MISSING_MONGO_URI}
server.servlet.context-path=/
server.port=${PORT:8080}
ai.api.key=${AI_API_KEY:test123}
spring.data.mongodb.auto-index-creation=true