spring.application.name=Employee Performance Monitoring
spring.data.mongodb.uri=mongodb+srv://sanjaykumarcsbs_db_user:SSTaJ7lGOLuFbezb@cluster0.5s7mcay.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0
server.servlet.context-path=/
server.port=${PORT:8080}
ai.api.key=${AI_API_KEY:test123}
spring.data.mongodb.auto-index-creation=false
