spring.application.name=Employee Performance Monitoring
spring.data.mongodb.uri=mongodb+srv://sanjaykumarcsbs_db_user:root@cluster0.5s7mcay.mongodb.net/employeedb
server.servlet.context-path=/
ai.api.key=test123